In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('derm.csv')
dataset

erythema  scaling  definite_borders  itching  koebner_phenomenon  \
0           2        2                 0        3                   0   
1           3        3                 3        2                   1   
2           2        1                 2        3                   1   
3           2        2                 2        0                   0   
4           2        3                 2        2                   2   
5           2        3                 2        0                   0   
6           2        1                 0        2                   0   
7           2        2                 3        3                   3   
8           2        2                 1        0                   2   
9           2        2                 1        0                   1   
10          3        3                 2        1                   1   
11          2        2                 0        3                   0   
12          3        3                 1        2                   0   
13          2        3                 3        0                   0   
14          2        2                 3        3                   0   
15          1        1                 0        1                   3   
16          2        2                 1        3                   0   
17          3        3                 3        0                   0   
18          2        1                 3        3                   3   
19          1        1                 0        3                   0   
20          2        1                 1        2                   0   
21          3        2                 2        0                   0   
22          2        2                 0        2                   0   
23          2        2                 2        3                   2   
24          2        0                 0        3                   0   
25          2        1                 1        0                   1   
26          1        1                 0        1                   0   
27          1        2                 2        3                   0   
28          3        2                 2        2                   0   
29          1        1                 2        3                   2   
..        ...      ...               ...      ...                 ...   
336         2        3                 2        1                   0   
337         2        1                 0        0                   0   
338         3        1                 0        1                   0   
339         2        1                 2        2                   2   
340         2        2                 3        0                   0   
341         1        1                 0        2                   0   
342         2        0                 1        2                   0   
343         2        2                 2        0                   0   
344         2        2                 1        0                   0   
345         2        2                 2        1                   1   
346         2        2                 2        1                   0   
347         2        2                 0        1                   0   
348         3        2                 2        0                   0   
349         2        2                 1        0                   0   
350         1        2                 2        2                   0   
351         2        2                 2        3                   2   
352         3        2                 2        3                   2   
353         1        1                 1        2                   0   
354         2        0                 1        2                   0   
355         2        3                 2        3                   2   
356         2        2                 2        2                   2   
357         2        2                 2        0                   1   
358         2        3                 2        1              

In [3]:
X = dataset.iloc[:, 0:34].values
y = dataset.iloc[:, 34].values

In [4]:
X

array([[ 2,  2,  0, ...,  1,  0, 55],
       [ 3,  3,  3, ...,  1,  0,  8],
       [ 2,  1,  2, ...,  2,  3, 26],
       ...,
       [ 3,  2,  2, ...,  2,  3, 28],
       [ 2,  1,  3, ...,  2,  3, 50],
       [ 3,  2,  2, ...,  3,  0, 35]], dtype=int64)

In [5]:
y

array([2, 1, 3, 1, 3, 2, 5, 3, 4, 4, 1, 2, 2, 1, 3, 4, 2, 1, 3, 5, 6, 2,
       5, 3, 5, 1, 6, 5, 2, 3, 1, 2, 1, 1, 4, 2, 3, 2, 3, 1, 2, 4, 1, 2,
       5, 3, 4, 6, 2, 3, 3, 4, 1, 1, 5, 1, 2, 3, 4, 2, 6, 1, 5, 1, 2, 3,
       1, 4, 5, 1, 2, 6, 3, 5, 4, 2, 2, 1, 3, 5, 1, 2, 2, 2, 5, 1, 1, 3,
       1, 4, 2, 2, 5, 1, 3, 4, 2, 5, 1, 6, 2, 5, 1, 2, 2, 1, 4, 1, 3, 1,
       1, 3, 5, 3, 3, 5, 2, 3, 4, 1, 2, 5, 6, 1, 1, 2, 6, 3, 5, 4, 1, 1,
       3, 5, 5, 1, 4, 2, 3, 1, 2, 1, 1, 3, 3, 3, 2, 5, 4, 2, 2, 1, 1, 1,
       5, 3, 2, 3, 2, 2, 4, 2, 3, 6, 2, 1, 1, 3, 4, 3, 3, 1, 1, 1, 3, 1,
       1, 2, 3, 3, 1, 1, 1, 1, 6, 2, 2, 2, 2, 1, 3, 3, 3, 1, 1, 2, 3, 2,
       2, 2, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 4, 4,
       4, 4, 5, 5, 5, 5, 5, 5, 5, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 6, 6, 1,
       1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 5,
       5, 5, 6, 6, 6, 4, 4, 4, 1, 1, 1, 1, 1, 2, 2, 4, 4, 4, 1, 1, 2, 2,
       2, 3, 3, 3, 3, 1, 1, 1, 1, 5, 5, 5, 5, 5, 3,

In [6]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X = sc_X.fit_transform(X)
X

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[-0.1028946 ,  0.29250271, -1.70937509, ..., -1.19445878,
        -0.50221531,  1.23623031],
       [ 1.40348234,  1.71991595,  1.60084334, ..., -1.19445878,
        -0.50221531, -1.86914845],
       [-0.1028946 , -1.13491053,  0.49743719, ...,  0.18463243,
         2.2142005 , -0.67985446],
       ...,
       [ 1.40348234,  0.29250271,  0.49743719, ...,  0.18463243,
         2.2142005 , -0.54771068],
       [-0.1028946 , -1.13491053,  1.60084334, ...,  0.18463243,
         2.2142005 ,  0.90587086],
       [ 1.40348234,  0.29250271,  0.49743719, ...,  1.56372365,
        -0.50221531, -0.08520746]])

In [7]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 5)
X = pca.fit_transform(X)
explained_variance = pca.explained_variance_ratio_
explained_variance

array([0.27175631, 0.16124123, 0.09141161, 0.06565121, 0.03942374])

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [9]:
X_train

array([[-3.88841732,  2.52083263,  0.99827619,  0.01195995, -0.47073266],
       [-4.25632919,  2.41399577,  0.52438006,  0.93037491,  0.49896398],
       [ 0.92555607, -2.65442223, -0.57233869, -1.39483118,  1.5449015 ],
       ...,
       [ 5.50481212,  2.3460577 , -0.06631841,  0.55799089, -0.32533906],
       [-1.2385973 , -1.97230605,  3.11862489,  0.85579342,  1.37366845],
       [-3.48573662,  1.61639077, -0.34623296, -1.90507611,  0.19689727]])

In [10]:
y_train

array([1, 1, 4, 1, 1, 1, 2, 3, 2, 3, 4, 5, 1, 5, 4, 4, 3, 5, 1, 2, 5, 4,
       2, 1, 5, 2, 5, 2, 5, 1, 1, 3, 3, 1, 1, 4, 2, 1, 2, 2, 6, 3, 3, 2,
       5, 2, 1, 1, 4, 6, 1, 3, 6, 1, 5, 1, 3, 1, 4, 4, 1, 5, 1, 3, 1, 3,
       1, 2, 4, 3, 4, 1, 1, 5, 2, 6, 3, 1, 3, 4, 1, 5, 1, 5, 2, 1, 2, 1,
       3, 3, 1, 1, 3, 2, 2, 3, 1, 1, 5, 1, 4, 1, 3, 1, 3, 5, 3, 4, 5, 4,
       6, 5, 4, 1, 3, 4, 2, 2, 2, 1, 3, 4, 4, 1, 5, 1, 2, 3, 1, 2, 1, 2,
       1, 5, 1, 3, 1, 2, 3, 2, 3, 1, 4, 3, 1, 5, 5, 4, 1, 1, 2, 5, 1, 1,
       5, 2, 1, 3, 2, 5, 1, 1, 2, 2, 6, 5, 1, 4, 5, 3, 1, 1, 1, 1, 4, 3,
       2, 2, 4, 1, 1, 3, 6, 4, 4, 3, 1, 4, 3, 3, 1, 5, 5, 1, 1, 2, 3, 2,
       2, 5, 4, 1, 3, 4, 3, 1, 4, 1, 3, 1, 2, 1, 4, 5, 4, 3, 1, 1, 4, 3,
       5, 5, 5, 5, 3, 5, 2, 2, 6, 1, 1, 3, 4, 4, 1, 1, 1, 4, 3, 1, 3, 5,
       3, 2, 1, 6, 1, 1, 5, 2, 1, 3, 2, 3, 3, 1, 5, 2, 6, 2, 6, 1, 2, 1,
       5, 5, 3, 5, 1, 1, 5, 1, 3, 5, 1, 1, 3, 1, 2, 3, 1, 1, 2, 1, 4, 2,
       3, 1, 3, 3, 6, 1], dtype=int64)

In [11]:
X_test

array([[ 8.79925688e-01, -2.70462311e+00, -1.39453739e+00,
        -3.68905731e-01,  2.59249513e+00],
       [ 3.52749068e-01, -1.68066343e+00, -1.83446914e-01,
        -9.60895012e-01,  3.77413430e-01],
       [ 4.60687955e+00,  1.56422304e+00,  2.00188845e-01,
         8.42992144e-01,  3.22830224e-01],
       [-4.46319754e-01, -4.47917626e+00,  6.28581644e+00,
         2.02319824e+00,  9.97726663e-01],
       [ 5.32264878e+00,  1.14138829e-01, -1.25522430e-01,
         1.42590448e+00,  1.58382504e+00],
       [-1.75415860e-01, -4.04240474e+00,  5.53436854e+00,
         5.22696286e-01, -5.82258233e-01],
       [ 1.23306331e-01, -1.75182223e+00, -7.41297595e-01,
        -2.90476997e+00, -1.01949830e+00],
       [-3.05980808e+00,  1.55760033e+00, -2.04215467e-01,
         6.61737948e-01, -4.65121599e-01],
       [-1.38957124e+00, -2.47838056e+00,  6.98605618e+00,
         1.90299305e-01, -9.86709140e-01],
       [ 3.46453591e-02, -2.59015352e+00, -1.78080273e+00,
         2.79052140e+00

In [12]:
y_test

array([4, 4, 3, 6, 3, 6, 2, 1, 6, 5, 2, 1, 5, 2, 5, 1, 1, 5, 4, 2, 1, 2,
       2, 1, 3, 3, 5, 4, 3, 3, 1, 1, 4, 2, 5, 2, 6, 3, 5, 2, 1, 4, 3, 4,
       6, 1, 3, 3, 6, 3, 1, 4, 1, 2, 5, 1, 1, 1, 4, 2, 3, 4, 3, 2, 3, 6,
       2, 6, 4, 2, 4, 3, 3, 5], dtype=int64)

In [13]:
from sklearn.linear_model import LogisticRegression
logisticregressionclassifier = LogisticRegression(random_state = 0)
logisticregressionclassifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [15]:
logisticregression_y_pred = logisticregressionclassifier.predict(X_test)
logisticregression_y_pred

array([4, 2, 3, 6, 3, 6, 2, 1, 6, 5, 2, 1, 5, 2, 5, 1, 1, 5, 4, 4, 1, 2,
       2, 1, 3, 3, 5, 2, 3, 3, 1, 1, 4, 2, 5, 2, 6, 3, 5, 2, 1, 4, 3, 4,
       6, 1, 3, 3, 6, 3, 1, 2, 1, 2, 5, 1, 1, 1, 4, 2, 3, 2, 3, 2, 3, 6,
       2, 6, 2, 2, 4, 3, 3, 5], dtype=int64)

In [16]:
from sklearn.metrics import confusion_matrix
logisticregression_cm = confusion_matrix(y_test, logisticregression_y_pred)
logisticregression_cm

array([[15,  0,  0,  0,  0,  0],
       [ 0, 13,  0,  1,  0,  0],
       [ 0,  0, 16,  0,  0,  0],
       [ 0,  5,  0,  7,  0,  0],
       [ 0,  0,  0,  0,  9,  0],
       [ 0,  0,  0,  0,  0,  8]], dtype=int64)

In [17]:
from sklearn.tree import DecisionTreeClassifier
decisiontreeclassifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
decisiontreeclassifier.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [18]:
decisiontree_y_pred = decisiontreeclassifier.predict(X_test)
decisiontree_y_pred

array([2, 4, 3, 5, 3, 6, 2, 1, 6, 5, 2, 1, 5, 2, 5, 1, 1, 5, 4, 4, 1, 2,
       2, 1, 3, 3, 5, 4, 3, 3, 1, 1, 4, 2, 5, 2, 6, 3, 5, 4, 1, 4, 3, 4,
       6, 1, 3, 3, 6, 3, 1, 2, 1, 2, 5, 1, 1, 1, 4, 2, 3, 4, 3, 4, 3, 6,
       4, 6, 4, 2, 4, 3, 3, 5], dtype=int64)

In [19]:
decisiontree_cm = confusion_matrix(y_test, decisiontree_y_pred)
decisiontree_cm

array([[15,  0,  0,  0,  0,  0],
       [ 0, 10,  0,  4,  0,  0],
       [ 0,  0, 16,  0,  0,  0],
       [ 0,  2,  0, 10,  0,  0],
       [ 0,  0,  0,  0,  9,  0],
       [ 0,  0,  0,  0,  1,  7]], dtype=int64)

In [20]:
from sklearn.ensemble import RandomForestClassifier
randomforestclassifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
randomforestclassifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [21]:
randomforest_y_pred = randomforestclassifier.predict(X_test)
randomforest_y_pred

array([4, 2, 3, 6, 3, 6, 2, 1, 6, 5, 2, 1, 5, 2, 5, 1, 1, 5, 4, 4, 1, 2,
       2, 1, 3, 3, 5, 4, 3, 3, 1, 1, 4, 2, 5, 2, 6, 3, 5, 2, 1, 4, 3, 4,
       6, 1, 3, 3, 6, 3, 1, 2, 1, 2, 5, 1, 1, 1, 4, 2, 3, 2, 3, 2, 3, 6,
       2, 6, 4, 2, 4, 3, 3, 5], dtype=int64)

In [22]:
randomforest_cm = confusion_matrix(y_test, randomforest_y_pred)
randomforest_cm

array([[15,  0,  0,  0,  0,  0],
       [ 0, 13,  0,  1,  0,  0],
       [ 0,  0, 16,  0,  0,  0],
       [ 0,  3,  0,  9,  0,  0],
       [ 0,  0,  0,  0,  9,  0],
       [ 0,  0,  0,  0,  0,  8]], dtype=int64)

In [23]:
from sklearn.svm import SVC
svmclassifier = SVC(kernel = 'linear', random_state = 0)
svmclassifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=0, shrinking=True,
  tol=0.001, verbose=False)

In [24]:
svm_y_pred = svmclassifier.predict(X_test)
svm_y_pred

array([4, 4, 3, 6, 3, 6, 2, 1, 6, 5, 2, 1, 5, 2, 5, 1, 1, 5, 4, 4, 1, 2,
       2, 1, 3, 3, 5, 4, 3, 3, 1, 1, 4, 2, 5, 2, 6, 3, 5, 2, 1, 4, 3, 4,
       6, 1, 3, 3, 6, 3, 1, 4, 1, 2, 5, 1, 1, 1, 4, 2, 3, 4, 3, 2, 3, 6,
       2, 6, 2, 2, 4, 3, 3, 5], dtype=int64)

In [25]:
svm_cm = confusion_matrix(y_test, svm_y_pred)
svm_cm

array([[15,  0,  0,  0,  0,  0],
       [ 0, 13,  0,  1,  0,  0],
       [ 0,  0, 16,  0,  0,  0],
       [ 0,  1,  0, 11,  0,  0],
       [ 0,  0,  0,  0,  9,  0],
       [ 0,  0,  0,  0,  0,  8]], dtype=int64)