In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv('derm.csv')
dataset

erythema  scaling  definite_borders  itching  koebner_phenomenon  \
0           2        2                 0        3                   0   
1           3        3                 3        2                   1   
2           2        1                 2        3                   1   
3           2        2                 2        0                   0   
4           2        3                 2        2                   2   
5           2        3                 2        0                   0   
6           2        1                 0        2                   0   
7           2        2                 3        3                   3   
8           2        2                 1        0                   2   
9           2        2                 1        0                   1   
10          3        3                 2        1                   1   
11          2        2                 0        3                   0   
12          3        3                 1        2                   0   
13          2        3                 3        0                   0   
14          2        2                 3        3                   0   
15          1        1                 0        1                   3   
16          2        2                 1        3                   0   
17          3        3                 3        0                   0   
18          2        1                 3        3                   3   
19          1        1                 0        3                   0   
20          2        1                 1        2                   0   
21          3        2                 2        0                   0   
22          2        2                 0        2                   0   
23          2        2                 2        3                   2   
24          2        0                 0        3                   0   
25          2        1                 1        0                   1   
26          1        1                 0        1                   0   
27          1        2                 2        3                   0   
28          3        2                 2        2                   0   
29          1        1                 2        3                   2   
..        ...      ...               ...      ...                 ...   
336         2        3                 2        1                   0   
337         2        1                 0        0                   0   
338         3        1                 0        1                   0   
339         2        1                 2        2                   2   
340         2        2                 3        0                   0   
341         1        1                 0        2                   0   
342         2        0                 1        2                   0   
343         2        2                 2        0                   0   
344         2        2                 1        0                   0   
345         2        2                 2        1                   1   
346         2        2                 2        1                   0   
347         2        2                 0        1                   0   
348         3        2                 2        0                   0   
349         2        2                 1        0                   0   
350         1        2                 2        2                   0   
351         2        2                 2        3                   2   
352         3        2                 2        3                   2   
353         1        1                 1        2                   0   
354         2        0                 1        2                   0   
355         2        3                 2        3                   2   
356         2        2                 2        2                   2   
357         2        2                 2        0                   1   
358         2        3                 2        1              

In [4]:
X = dataset.iloc[:, 0:34].values
y = dataset.iloc[:, 34].values

In [5]:
X

array([[ 2,  2,  0, ...,  1,  0, 55],
       [ 3,  3,  3, ...,  1,  0,  8],
       [ 2,  1,  2, ...,  2,  3, 26],
       ...,
       [ 3,  2,  2, ...,  2,  3, 28],
       [ 2,  1,  3, ...,  2,  3, 50],
       [ 3,  2,  2, ...,  3,  0, 35]], dtype=int64)

In [6]:
y

array([2, 1, 3, 1, 3, 2, 5, 3, 4, 4, 1, 2, 2, 1, 3, 4, 2, 1, 3, 5, 6, 2,
       5, 3, 5, 1, 6, 5, 2, 3, 1, 2, 1, 1, 4, 2, 3, 2, 3, 1, 2, 4, 1, 2,
       5, 3, 4, 6, 2, 3, 3, 4, 1, 1, 5, 1, 2, 3, 4, 2, 6, 1, 5, 1, 2, 3,
       1, 4, 5, 1, 2, 6, 3, 5, 4, 2, 2, 1, 3, 5, 1, 2, 2, 2, 5, 1, 1, 3,
       1, 4, 2, 2, 5, 1, 3, 4, 2, 5, 1, 6, 2, 5, 1, 2, 2, 1, 4, 1, 3, 1,
       1, 3, 5, 3, 3, 5, 2, 3, 4, 1, 2, 5, 6, 1, 1, 2, 6, 3, 5, 4, 1, 1,
       3, 5, 5, 1, 4, 2, 3, 1, 2, 1, 1, 3, 3, 3, 2, 5, 4, 2, 2, 1, 1, 1,
       5, 3, 2, 3, 2, 2, 4, 2, 3, 6, 2, 1, 1, 3, 4, 3, 3, 1, 1, 1, 3, 1,
       1, 2, 3, 3, 1, 1, 1, 1, 6, 2, 2, 2, 2, 1, 3, 3, 3, 1, 1, 2, 3, 2,
       2, 2, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 4, 4,
       4, 4, 5, 5, 5, 5, 5, 5, 5, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 6, 6, 1,
       1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 5,
       5, 5, 6, 6, 6, 4, 4, 4, 1, 1, 1, 1, 1, 2, 2, 4, 4, 4, 1, 1, 2, 2,
       2, 3, 3, 3, 3, 1, 1, 1, 1, 5, 5, 5, 5, 5, 3,

In [7]:
X[:, 33]

array([55,  8, 26, 40, 45, 41, 18, 57, 22, 30, 20, 21, 22, 10, 65, 40, 30,
       38, 23, 17,  8, 51, 42, 44, 22, 33, 10, 17, 43, 50, 50, 10, 34, 36,
       36, 36, 36, 15, 26, 46, 51, 62, 15, 35, 30, 48, 46, 12, 52, 60, 32,
       35, 41, 48, 51, 19, 22, 29, 25, 33,  8, 40, 33, 42, 36, 60, 36, 21,
       40, 21, 34, 13, 52, 48, 17, 25, 33, 62, 52, 27, 40, 31, 27, 10, 55,
       30, 42, 48, 22, 31, 50, 43, 30, 42, 22, 18, 35, 60, 28, 13, 20, 64,
       43, 20, 34, 39, 60, 38, 44, 36, 41, 18, 39, 40, 47, 16, 27, 52, 25,
        0, 33, 46,  7, 30, 29, 23,  8, 44, 17, 16, 55, 40, 34, 29, 34, 25,
       70, 37, 41, 32, 20, 19, 61, 27, 36, 40, 52, 27, 30, 45, 34, 27, 46,
       52, 28, 40, 55, 32, 33, 47, 35, 61, 22, 10, 20, 55, 67, 51, 20, 22,
       45, 55, 56, 18, 40, 30, 33, 40, 42, 36, 27, 56, 60, 20,  7, 30, 19,
       52, 55, 23, 50, 38, 25, 18, 35, 22, 52, 50, 33, 44, 18, 25, 52, 35,
       40, 55, 20, 60, 33, 27, 50, 70, 28, 30, 53, 27, 50, 42, 45, 35, 30,
       42, 18, 25, 36, 40

In [8]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [11]:
test = SelectKBest(score_func=chi2, k=4)
fit = test.fit(X, y)

np.set_printoptions(precision=3)
print(fit.scores_)

outcome = fit.get_support()


features = fit.transform(X)
print(features[0:5,:])

for i in range(len(outcome)):
    if outcome[i]:
        #print(i)
        print(fit.scores_[i])

[ 12.683  28.571  73.882 111.247 161.801 669.667 537.371 563.5   356.051
 324.209  67.812 604.333  60.14  188.149 688.    198.654  12.81   47.426
  71.246 513.124 401.305 513.184 176.647 276.275 577.996 199.666 671.8
 275.436 667.742 552.411 690.579   8.905 759.365 431.095]
[[0 0 0 0]
 [0 0 0 0]
 [0 2 0 3]
 [0 0 0 0]
 [0 3 0 3]]
687.9998957681885
671.8000071286002
690.5785714285715
759.3649384687561


In [12]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X = sc_X.fit_transform(X)
X

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[-0.103,  0.293, -1.709, ..., -1.194, -0.502,  1.236],
       [ 1.403,  1.72 ,  1.601, ..., -1.194, -0.502, -1.869],
       [-0.103, -1.135,  0.497, ...,  0.185,  2.214, -0.68 ],
       ...,
       [ 1.403,  0.293,  0.497, ...,  0.185,  2.214, -0.548],
       [-0.103, -1.135,  1.601, ...,  0.185,  2.214,  0.906],
       [ 1.403,  0.293,  0.497, ...,  1.564, -0.502, -0.085]])

In [13]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 5)
X = pca.fit_transform(X)
explained_variance = pca.explained_variance_ratio_

In [14]:
explained_variance

array([0.272, 0.161, 0.091, 0.066, 0.039])